apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sjon1111/Java-devops-project.git
    targetRevision: main
    path: k8s/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
