apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: qa
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: Test@123
